### ISSUE TITLE
confuse about setup the steering wheel

### ISSUE THREAD

**Issue by Co2Link** [Check2016/gta-v-driver#1]
```
Enable and setup the steering wheel of the manual transmission mod with the x360ce(vJoy) controller 
```
could author be more explicit about how this set was done?

**Comment by mrclgl** [comment]
Very late reply, but better late than never... I meant the ingame setup of the controller with the manual transmission mod. In order to use a steering wheel in GTA with this mod, you need to calibrate it ingame. You could figure it out just from browsing the menus of the mod, but I'm pretty sure there is documentation on that for setting up a controller/steering wheel. Hope that clears it up ^^

If there's anything else thats unclear or you want to know, feel free to ask!
